---
- name: Install the basic packages
  yum:
    name:
      - nginx
      - policycoreutils-python-utils

- name: create user {{nginx_user}}
  user:
    name: "{{nginx_user}}"
    comment: "{{nginx_user}}"
    create_home: false

- name: Create directories - Nginx Config
  file:
    path: /etc/nginx/{{ item.path }}
    state: directory
    force: yes
  with_filetree: ../templates/nginx/
  when: item.state != 'file'

- name: Creates files - Config Nginx
  template:
    src: '{{ item.src }}'
    dest: /etc/nginx/{{ item.path }}
    force: yes
  with_filetree: ../templates/nginx/
  when: item.state == 'file'
  notify: restart nginx

- name: Set httpd_can_network_connect flag on and keep it persistent across reboots
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  notify: restart nginx

- name: Set httpd_setrlimit flag on and keep it persistent across reboots
  seboolean:
    name: httpd_setrlimit
    state: yes
    persistent: yes
  notify: restart nginx
